#!/usr/bin/env python3
"""Download Google Fonts woff2 files locally and emit a self-hosted @font-face stylesheet.

Preserves Google's unicode-range subsetting, so Arabic and Latin load independently —
an English page never downloads the Arabic glyphs and vice versa.
"""
import re
import pathlib
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTDIR = ROOT / "public" / "fonts"
OUT = ROOT / "src" / "styles" / "fonts.css"

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

FAMILIES = [
    ("Reem+Kufi",            "wght@400..700"),     # Arabic display (variable)
    ("Amiri",                "wght@400;700"),      # Arabic reading (static)
    ("IBM+Plex+Sans+Arabic", "wght@400;500;600"),  # Arabic UI / nav / small
    ("Oswald",               "wght@200..700"),     # Latin display (variable, condensed)
    ("IBM+Plex+Sans",        "wght@400;500;600"),  # Latin reading
    ("IBM+Plex+Mono",        "wght@400;500"),      # metadata mono
]


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req, timeout=60).read()


def main():
    FONTDIR.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    chunks = []
    for fam, axis in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={fam}:{axis}&display=swap").decode()
        urls = sorted(set(re.findall(r"url\((https://[^)]+\.woff2)\)", css)))
        print(f"{fam:18} {len(urls):2} files")
        for u in urls:
            # stable local name from the google path: .../s/reemkufi/v27/abc.woff2
            parts = u.rstrip("/").split("/")
            name = f"{parts[-3]}-{parts[-2]}-{parts[-1]}"
            dest = FONTDIR / name
            if not dest.exists():
                dest.write_bytes(get(u))
            css = css.replace(u, f"/fonts/{name}")
        chunks.append(f"/* ---- {fam.replace('+', ' ')} ---- */\n{css.strip()}")

    OUT.write_text(
        "/* Generated by scripts/fetch-fonts.py - do not edit by hand. */\n\n"
        + "\n\n".join(chunks) + "\n"
    )

    files = list(FONTDIR.glob("*.woff2"))
    total = sum(f.stat().st_size for f in files)
    print(f"\n{len(files)} woff2 files, {total / 1024:.0f} KB total")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
